version: '3'
services:
  ms:
    image: vipermsf:latest
    command: ['thin', '--rackup', 'msf-json-rpc.ru', '--address', '0.0.0.0', '--port', '8081', '--environment', 'development', '--tag', 'msf-json-rpc', 'start']
    environment:
      - MSF_CFGROOT_CONFIG=/home/msf/.msf4
      - MSF_WS_DATA_SERVICE_LOGGER=Stdout
      - MSF_UID
      - MSF_GID
      - LHOST
    depends_on:
      - db
      - redis
    ports:
      - 8081:8081
    volumes:
      - ~msf/.msf4:/home/msf/.msf4

  db:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'venus!Postgres123'
  redis:
    image: redis:7-alpine
    command: [ 'redis-server', '--requirepass', 'venus!Redis123' ]
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
